version: 2
jobs:
  build:
    
    working_directory: ~/three-page-path

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: toy-robot-simulator-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: three-page-path-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/three-page-path-1.0-SNAPSHOT.jar
